# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f6c9a9b93c5842c38d33e780f9144bd5b47ca4df341919b06c605830f70c7e401f673f2e6c6aa2511961163894ba4c846455d7ac54c4c5dcb3d79829c91829a

test:
  secret_key_base: 57af72d4cd3a598e95cd4a8d468d5ae6ff766ffd2e4aad1b9a04c6cc3db847b7de6c1c0f89db2235e990e76132570c2c16810aacc37302a4351a071ad1a647b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
